name: ACR Build and Push

on: 
  push:
    branches: master
    
env:
  REGISTRY: travisjregistry.azurecr.io
  IMAGE_NAME: myimage
  VAULT_NAME: travisj-kv
  CERT_NAME: Sectigo
  GODEBUG: x509sha1=1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0
        
      - 
        name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_GITHUB_CREDS }}

      -
        name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID_GH }}
          password: ${{ secrets.AZURE_CLIENT_SECRET_GH }}

      -
        name: Install ORAS CLI
        run: | 
          curl -Lo oras.tar.gz https://github.com/oras-project/oras/releases/download/v0.16.0/oras_0.16.0_linux_amd64.tar.gz
          tar -xzf oras.tar.gz 
          mv ./oras /usr/local/bin/

      -
        name: Install Notation CLI
        run: |
          curl -Lo notation.tar.gz https://github.com/notaryproject/notation/releases/download/v1.0.0-rc.1/notation_1.0.0-rc.1_linux_amd64.tar.gz
          tar -xzf notation.tar.gz
          mv ./notation /usr/local/bin
          
      -
        name: Install Notation AKV Plugin
        run: |
          mkdir -p ~/.config/notation/plugins/azure-kv
          curl -Lo notation-azure-kv.tar.gz https://github.com/Azure/notation-azure-kv/releases/download/v0.5.0-rc.1/notation-azure-kv_0.5.0-rc.1_Linux_amd64.tar.gz
          tar -xzf notation-azure-kv.tar.gz -C ~/.config/notation/plugins/azure-kv notation-azure-kv
       
      -
        name: Configure Notation AKV plugin
        run: |
          KEY_ID=$(az keyvault certificate show -n ${{ env.CERT_NAME }} --vault-name ${{ env.VAULT_NAME }} --query 'kid' -o tsv)
          notation key add --plugin azure-kv --id $KEY_ID --default ${{ env.CERT_NAME }}

      - 
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.2.1

      - 
        name: Generate metadata for Docker image
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }} 
          tags: ${{ steps.meta.outputs.tags }}
          
      -
        name: Sign Docker image
        run: |
          notation sign --signature-format cose -u ${{ secrets.AZURE_CLIENT_ID_GH }} -p ${{ secrets.AZURE_CLIENT_SECRET_GH }} ${{ steps.meta.outputs.tags }} 
          oras discover ${{ steps.meta.outputs.tags }} -o tree
          SIG_DIGEST=$(oras discover ${{ steps.meta.outputs.tags }} --artifact-type application/vnd.cncf.notary.signature -o json | jq -r ".manifests[0].digest")
          BLOB_DIGEST=$(oras manifest fetch ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$SIG_DIGEST | jq -r ".blobs[0].digest")
          oras blob fetch --output signature.cose ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@$BLOB_DIGEST
      
      -
        name: Submit signature to SCITT
        run: | 
          oras pull travisjregistry.azurecr.io/scitt:preview
          chmod +x ./scitt
          ./scitt submit --signature signature.cose --service-name test --output receipt.scitt --format json
          oras attach ${{ steps.meta.outputs.tags }} receipt.scitt --artifact-type application/json
      
      - 
        name: Generate and attach SBOM 
        run: |
          curl -Lo sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x ./sbom-tool
          ./sbom-tool generate -BuildDropPath . -BuildComponentPath . -PackageName ${{ github.event.repository.name }} -PackageVersion 1.0.0 -PackageSupplier TravisJCo -NamespaceUriBase https://sbom.travisjco.com -V Verbose
          oras attach ${{ steps.meta.outputs.tags }} _manifest/spdx_2.2/manifest.spdx.json --artifact-type application/spdx+json

      - 
        name: Publish artifacts and signatures
        uses: actions/upload-artifact@v3.1.1
        with:
          path: |
            _manifest/spdx_2.2/manifest.spdx.json
            signature.cose
            receipt.scitt
           
