name: GHCR Build and Push

on: 
  push:
    branches: master
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: myimage

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0
        
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Install ORAS CLI
        run: | 
          curl -Lo oras.tar.gz https://github.com/oras-project/oras/releases/download/v0.15.0/oras_0.15.0_linux_amd64.tar.gz
          tar -xzf oras.tar.gz 
          mv ./oras /usr/local/bin/

      - 
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.2.1

      - 
        name: Generate metadata for Docker image
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }} 
          tags: ${{ steps.meta.outputs.tags }}
          
